name: Maven CI with Test Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn clean test

      - name: Generate full Maven site (includes Surefire report)
        run: mvn site

      - name: Debug: List target/site contents
        run: ls -R target/site

      - name: Upload Surefire HTML report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/site/surefire-report.html
